#!/bin/bash
# tuning.sh - Kernel/sysctl tuning for streaming workloads
# Part of swizzin-scripts bootstrap

# ==============================================================================
# Sysctl Configuration
# ==============================================================================

configure_sysctl() {
    echo_header "Kernel Tuning"

    # Backup existing sysctl config
    backup_file "/etc/sysctl.conf" "/opt/swizzin/bootstrap-backups/sysctl"

    echo_progress_start "Configuring sysctl for streaming"

    cat > /etc/sysctl.d/99-streaming.conf <<'EOF'
# Bootstrap Sysctl Configuration for Streaming
# Generated by swizzin-scripts bootstrap

# ==============================================================================
# TCP/Network Optimization
# ==============================================================================

# Increase TCP buffer sizes for high-throughput streaming
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.core.rmem_default = 65536
net.core.wmem_default = 65536

# TCP memory settings (min, default, max)
net.ipv4.tcp_rmem = 4096 87380 134217728
net.ipv4.tcp_wmem = 4096 65536 134217728

# Enable BBR congestion control (better for streaming over WAN)
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# Enable TCP Fast Open
net.ipv4.tcp_fastopen = 3

# Disable slow start after idle (better for streaming)
net.ipv4.tcp_slow_start_after_idle = 0

# Increase connection backlog
net.core.somaxconn = 65535
net.core.netdev_max_backlog = 65535

# TCP keepalive settings
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_intvl = 60
net.ipv4.tcp_keepalive_probes = 5

# Time-wait sockets
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15

# SYN flood protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 65535

# ==============================================================================
# Connection Tracking (for many concurrent streams)
# ==============================================================================

# Increase conntrack table size
net.netfilter.nf_conntrack_max = 262144

# Reduce conntrack timeout for faster cleanup
net.netfilter.nf_conntrack_tcp_timeout_established = 86400
net.netfilter.nf_conntrack_tcp_timeout_time_wait = 30

# ==============================================================================
# Memory Management
# ==============================================================================

# Reduce swappiness (prefer RAM over swap for active streams)
vm.swappiness = 10

# Reduce VFS cache pressure (keep directory caches longer)
vm.vfs_cache_pressure = 50

# Dirty page ratios for write buffering
vm.dirty_ratio = 15
vm.dirty_background_ratio = 5

# Overcommit memory settings
vm.overcommit_memory = 1
vm.overcommit_ratio = 50

# ==============================================================================
# File System
# ==============================================================================

# Increase system-wide file descriptor limit
fs.file-max = 2097152

# Increase inotify limits (for *arr apps monitoring)
fs.inotify.max_user_watches = 524288
fs.inotify.max_user_instances = 1024
fs.inotify.max_queued_events = 32768

# ==============================================================================
# Security (additional hardening)
# ==============================================================================

# Disable IP forwarding (unless needed for containers)
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Ignore source-routed packets
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0

# Enable reverse path filtering
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Log martian packets
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1
EOF

    echo_progress_done "Sysctl configuration created"

    # Load BBR module
    echo_progress_start "Loading BBR module"
    if ! lsmod | grep -q tcp_bbr; then
        modprobe tcp_bbr 2>/dev/null || echo_warn "BBR module not available"
    fi

    # Persist BBR module
    if ! grep -q "tcp_bbr" /etc/modules-load.d/*.conf 2>/dev/null; then
        echo "tcp_bbr" > /etc/modules-load.d/bbr.conf
    fi
    echo_progress_done "BBR module configured"

    # Apply settings
    echo_progress_start "Applying sysctl settings"
    if sysctl --system &>/dev/null; then
        echo_progress_done "Sysctl settings applied"
    else
        echo_progress_fail "Some settings may have failed"
        echo_warn "Check dmesg for errors"
    fi

    echo_success "Kernel tuning complete"
}

# ==============================================================================
# File Descriptor Limits
# ==============================================================================

configure_limits() {
    echo_header "System Limits Configuration"

    # Backup existing limits
    backup_file "/etc/security/limits.conf" "/opt/swizzin/bootstrap-backups/limits"

    echo_progress_start "Configuring file descriptor limits"

    cat > /etc/security/limits.d/99-streaming.conf <<'EOF'
# Bootstrap Limits Configuration for Streaming
# Generated by swizzin-scripts bootstrap

# File descriptor limits
* soft nofile 1048576
* hard nofile 1048576
root soft nofile 1048576
root hard nofile 1048576

# Process limits
* soft nproc 65535
* hard nproc 65535
root soft nproc 65535
root hard nproc 65535

# Memory lock (for some applications)
* soft memlock unlimited
* hard memlock unlimited
EOF

    echo_progress_done "Limits configuration created"

    # Configure systemd defaults
    echo_progress_start "Configuring systemd limits"

    mkdir -p /etc/systemd/system.conf.d
    cat > /etc/systemd/system.conf.d/99-limits.conf <<'EOF'
# Bootstrap Systemd Limits
# Generated by swizzin-scripts bootstrap

[Manager]
DefaultLimitNOFILE=1048576
DefaultLimitNPROC=65535
DefaultLimitMEMLOCK=infinity
EOF

    mkdir -p /etc/systemd/user.conf.d
    cat > /etc/systemd/user.conf.d/99-limits.conf <<'EOF'
# Bootstrap Systemd User Limits
# Generated by swizzin-scripts bootstrap

[Manager]
DefaultLimitNOFILE=1048576
DefaultLimitNPROC=65535
EOF

    echo_progress_done "Systemd limits configured"

    # Reload systemd
    systemctl daemon-reload

    echo_success "System limits configured"
    echo_info "Note: Some limits require a reboot to take full effect"
}

# ==============================================================================
# PAM Limits
# ==============================================================================

configure_pam_limits() {
    echo_progress_start "Configuring PAM limits"

    # Ensure pam_limits.so is enabled
    local pam_common_session="/etc/pam.d/common-session"
    local pam_common_session_noninteractive="/etc/pam.d/common-session-noninteractive"

    if [[ -f "$pam_common_session" ]]; then
        if ! grep -q "pam_limits.so" "$pam_common_session"; then
            echo "session required pam_limits.so" >> "$pam_common_session"
        fi
    fi

    if [[ -f "$pam_common_session_noninteractive" ]]; then
        if ! grep -q "pam_limits.so" "$pam_common_session_noninteractive"; then
            echo "session required pam_limits.so" >> "$pam_common_session_noninteractive"
        fi
    fi

    echo_progress_done "PAM limits configured"
}

# ==============================================================================
# FUSE Configuration (for rclone mounts)
# ==============================================================================

configure_fuse() {
    echo_header "FUSE Configuration"

    echo_progress_start "Configuring FUSE for rclone mounts"

    # Enable user_allow_other
    if [[ -f /etc/fuse.conf ]]; then
        if ! grep -q "^user_allow_other" /etc/fuse.conf; then
            echo "user_allow_other" >> /etc/fuse.conf
        fi
    else
        echo "user_allow_other" > /etc/fuse.conf
    fi

    # Increase FUSE max_background and congestion_threshold
    if [[ ! -f /etc/modprobe.d/fuse.conf ]]; then
        cat > /etc/modprobe.d/fuse.conf <<'EOF'
# FUSE configuration for better rclone performance
options fuse max_user_bgreq=1024
options fuse max_user_congthresh=768
EOF
    fi

    echo_progress_done "FUSE configured"

    echo_success "FUSE optimized for rclone mounts"
}

# ==============================================================================
# Disable Unnecessary Services
# ==============================================================================

disable_unnecessary_services() {
    echo_header "Disabling Unnecessary Services"

    local services_to_disable=(
        "snapd.service"
        "snapd.socket"
        "snapd.seeded.service"
        "multipathd.service"
        "ModemManager.service"
        "wpa_supplicant.service"
        "bluetooth.service"
        "cups.service"
        "cups-browsed.service"
        "avahi-daemon.service"
    )

    for service in "${services_to_disable[@]}"; do
        if systemctl is-enabled "$service" &>/dev/null; then
            echo_progress_start "Disabling $service"
            systemctl stop "$service" 2>/dev/null || true
            systemctl disable "$service" 2>/dev/null || true
            systemctl mask "$service" 2>/dev/null || true
            echo_progress_done "$service disabled"
        fi
    done

    echo_success "Unnecessary services disabled"
}

# ==============================================================================
# Run All Tuning
# ==============================================================================

run_tuning() {
    configure_sysctl
    configure_limits
    configure_pam_limits
    configure_fuse

    if ask "Disable unnecessary services (snapd, bluetooth, etc.)?" Y; then
        disable_unnecessary_services
    fi

    echo ""
    echo_success "All kernel tuning complete"
    echo_info "Some settings will take full effect after reboot"
}
